[project]
name = "earthworm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp==3.12.12",
    "beautifulsoup4==4.13.4",
    "praw>=7.8.1",
    "requests==2.32.4",
]
